dancing baby added
nss-cohort-37/c37-class-website pull request #9
Opened 2020-04-14 14:37 UTC by wggreen

## Link to Ticket

DANCINGBABY[https://github.com/nss-cohort-37/c37-class-website/compare/dancingbaby?expand=1]()

## Description of Proposed Changes

Dancing baby added

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout <dancingbaby>

Look at the dancing baby

## Impacted Areas in Application

The whole thing

* 

## Mentions @jansenv @jamesnitz @namitamanohar 

Tag users that need to review this code

2020-04-14 14:39 UTC, macgibbons requested changes
more baby 👶

2020-08-11 14:00 UTC, jansenv approved these changes

2020-08-11 14:01 UTC, jansenv approved these changes

2020-08-11 14:01 UTC, jansenv commented
wow, what a wonderful dancing baby

2020-08-11 14:01 UTC, merged